MVCcars/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVCcars.Models
{
    public class Employee
    {
        public string Id { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string Title { get; set; }
        public Address Address { get; set; }
        [Display(Name = "Hired At")]
        [DataType(DataType.Date)]
        public DateTime HiredAt { get; set; }
        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }

        [Display(Name = "Home Phone")]
        public string HomePhone { get; set; }
        public string Extension { get; set; }
        [NotMapped]
        public string ReportsTo { get; set; }
        [NotMapped]
        public List<string> Notes { get; set; }
        [NotMapped]
        public List<string> Territories { get; set; }

        public Employee()
        {

        }
    }
}

MVCcars/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCcars.Models;
using Raven.Client.Documents;

namespace MVCcars.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MVCcarsContext _context;

        public EmployeesController(MVCcarsContext context)
        {
            _context = context;
        }

        // GET: Employees
        public IActionResult Index(string searched)
        {
            using (var session = StoreHolder.Store.OpenSession())
            {
                var v = new GenericModelClassViewer<Employee>();
                if (!String.IsNullOrEmpty(searched))
                {
                    var q = session.Query<Employee,SearchIndex>()
                        .Customize(aq => aq.WaitForNonStaleResults(TimeSpan.FromSeconds(2))) //attende l'aggiornamento del db, aspetta che l'indice sia aggiornato
                        .Where(x => x.FirstName != null)
                        .Search(s => s.FirstName, "*" + searched + "*") 
                        .OrderBy(x => x.FirstName); //avendo indicizzato solo FirstName nella classe indice, non posso ordinare su FirstName, perchè non è ritornato dalla query
                    v.list = q.ToList();
                }
                else
                {
                    //in questa query non sto usando l'indice (secondo generics nel metodo query), quindi posso ordinare secondo LastName
                    v.list = session.Query<Employee>()
                        .Customize(aq => aq.WaitForNonStaleResults(TimeSpan.FromSeconds(2)))
                        .Where(x => x.FirstName != null).OrderBy(x => x.FirstName).ToList();
                }


                return View(v);
            }

        }

        // GET: Employees/Details/5
        public IActionResult Details(string id)
        {
            
            return MyViewCaller("Details", id);

        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,LastName,FirstName,Title,HiredAt,Birthday,HomePhone,Extension,ReportsTo")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                using (var session = StoreHolder.Store.OpenSession())
                {
                    session.Store(employee);
                    session.SaveChanges();

                }
                return RedirectToAction(nameof(Index));

            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public IActionResult Edit(string id)
        {
            
            return MyViewCaller("Edit", id);

        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("Id,LastName,FirstName,Title,HiredAt,Birthday,HomePhone,Extension,ReportsTo")] Employee employee)
        {
            if (id != employee.Id)
            {
                return RedirectToAction(nameof(Index));
            }
            AdjustId(ref id);
            if (ModelState.IsValid)
            {
                using (var session = StoreHolder.Store.OpenSession())
                {
                    employee.Id = id;
                    session.Store(employee);
                    session.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public IActionResult Delete(string id)
        {
            
            return MyViewCaller("Delete", id);

        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            AdjustId(ref id);
            using (var session = StoreHolder.Store.OpenSession())
            {
                session.Delete(id);
                session.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

        }
        private void AdjustId(ref string id)
        {
            id = "employees/" + id;
        }
       
        private IActionResult MyViewCaller(string view,string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }
            
            id = "employees/" + id;
            using (var session = StoreHolder.Store.OpenSession())
            {
                var employee = session.Query<Employee>().Where(x => x.Id.Equals(id)).FirstOrDefault();
                if (employee == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(view, employee);
            }
            
        }
       
    }
}

MVCcars/Views/Employees/Create.cshtml
@model MVCcars.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HiredAt" class="control-label"></label>
                <input asp-for="HiredAt" class="form-control" />
                <span asp-validation-for="HiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCcars/Views/Employees/Delete.cshtml
@model MVCcars.Models.Employee
@System.Globalization.CultureInfo.CurrentUICulture
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HiredAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HiredAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReportsTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportsTo)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCcars/Views/Employees/Details.cshtml
@model MVCcars.Models.Employee
@System.Globalization.CultureInfo.CurrentUICulture
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HiredAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HiredAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReportsTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReportsTo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id.Remove(0,10)">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCcars/Views/Employees/Edit.cshtml
@model MVCcars.Models.Employee
@System.Globalization.CultureInfo.CurrentUICulture
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HiredAt" class="control-label"></label>
                <input asp-for="HiredAt" class="form-control" />
                <span asp-validation-for="HiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Extension" class="control-label"></label>
                <input asp-for="Extension" class="form-control" />
                <span asp-validation-for="Extension" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportsTo" class="control-label"></label>
                <input asp-for="ReportsTo" class="form-control" />
                <span asp-validation-for="ReportsTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCcars/Views/Employees/Index.cshtml
@model MVCcars.Models.GenericModelClassViewer<Employee>

@{
    ViewData["Title"] = "Employee Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
    <form asp-controller="Employees" asp-action="Index" method="get">
        <p>
    Search by name: <input type="text" asp-for="Searched" />
    <input type="submit" value="Ordina Per" />
        </p>
    </form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.list[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].HiredAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].HomePhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Extension)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].ReportsTo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.list)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HiredAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomePhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extension)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReportsTo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id.Remove(0,10)">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id.Remove(0,10)">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id.Remove(0,10)">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>