MVCcars/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCcars.Models
{
    public class Company
    {
        public string Id { get; set; }
        public string ExternalId { get; set; }
        [Display(Name= "Company Name")]
        public string Name { get; set; }
        public Contact Contact { get; set; }
        public Address Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Company()
        {

        }
    }
}

MVCcars/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCcars.Models;
using Raven.Client.Documents;
using Raven.Client.Documents.Linq;
using Raven.Client.Documents.Session;

namespace MVCcars.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly MVCcarsContext _context;

        public CompaniesController(MVCcarsContext context)
        {
            _context = context;
        }

        // GET: Companies
        public IActionResult Index(string searched)
        {
            var x = new GenericModelClassViewer<Company>();

            using (var session = StoreHolder.Store.OpenSession())
            {
                var query = session.Query<Company>().Where(n => n.Name != null);

                if (!String.IsNullOrEmpty(searched))
                {
                    //wait for non stale ---attende l'aggiornamento del db, aspetta che l'indice sia aggiornato
                    //se non lo aggiungo, dopo che ho inserito un nuovo utente e sono ridirezionato ad Index, non vedo il nuovo inserimento
                    x.list = session.Query<Company>().Customize(q => q.WaitForNonStaleResults(TimeSpan.FromSeconds(2))).Search(r => r.Name, "*" + searched + "*").OrderBy(z => z.ExternalId).ToList();
                    
                }
                else
                {
                    x.list = query.Customize(q => q.WaitForNonStaleResults(TimeSpan.FromSeconds(2))).OrderBy(r => r.ExternalId).ToList();
                }

            }
            return View(x);
        }

        // GET: Companies/Details/5
        public  IActionResult Details(string id)
        {
            return MyViewCaller("Details", id);    
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,ExternalId,Name,Phone,Fax,Contact,Address")] Company company)
        {
            if (ModelState.IsValid)
            {
                using (var session = StoreHolder.Store.OpenSession())
                {
                    session.Store(company);
                    var i = company.Id;
                    session.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public IActionResult Edit(string id)
        {
            return MyViewCaller("Edit", id);
      
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("Id,ExternalId,Name,Phone,Fax,Contact,Address")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                id = "companies/" + id;
                using (var session = StoreHolder.Store.OpenSession())
                {
                    
                    company.Id = id;
                    session.Store(company);
                    session.SaveChanges();
                }
                
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public IActionResult Delete(string id)
        {
            return MyViewCaller("Delete", id);
            
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            using (var session = StoreHolder.Store.OpenSession())
            {
                id = "companies/" + id;
                
                session.Delete(id);
                session.SaveChanges();
            }
           
            return RedirectToAction(nameof(Index));
        }
        private void AdjustId(ref string id)
        {
            id = "companies/" + id;
        }

        private IActionResult MyViewCaller(string view, string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            id = "companies/" + id;
            using (var session = StoreHolder.Store.OpenSession())
            {
                var company = session.Query<Company>().Where(x => x.Id.Equals(id)).FirstOrDefault();
                if (company == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(view, company);
            }

        }

    }
}

MVCcars/Views/Companies/Create.cshtml
@model MVCcars.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExternalId" class="control-label"></label>
                <input asp-for="ExternalId" class="form-control" />
                <span asp-validation-for="ExternalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Contact.Name" class="control-label"></label>
                <input asp-for="Contact.Name" class="form-control" />
                <span asp-validation-for="Contact.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact.Title" class="control-label"></label>
                <input asp-for="Contact.Title" class="form-control" />
                <span asp-validation-for="Contact.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Region" class="control-label"></label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.PostalCode" class="control-label"></label>
                <input asp-for="Address.PostalCode" class="form-control" />
                <span asp-validation-for="Address.PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Line1" class="control-label"></label>
                <input asp-for="Address.Line1" class="form-control" />
                <span asp-validation-for="Address.Line1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Line2" class="control-label"></label>
                <input asp-for="Address.Line2" class="form-control" />
                <span asp-validation-for="Address.Line2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Location.Latitude" class="control-label"></label>
                <input asp-for="Address.Location.Latitude" class="form-control" />
                <span asp-validation-for="Address.Location.Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Location.Longitude" class="control-label"></label>
                <input asp-for="Address.Location.Longitude" class="form-control" />
                <span asp-validation-for="Address.Location.Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCcars/Views/Companies/Delete.cshtml
@model MVCcars.Models.Company
@System.Globalization.CultureInfo.CurrentUICulture

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExternalId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExternalId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Contact.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contact.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Contact.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contact.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Region)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Line1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Line1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Line2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Line2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Location.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Location.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Location.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Location.Longitude)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCcars/Views/Companies/Details.cshtml
@model MVCcars.Models.Company
@System.Globalization.CultureInfo.CurrentUICulture

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExternalId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExternalId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contact.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Contact.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contact.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Region)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Line1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Line1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Line2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Line2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Location.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Location.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address.Location.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Location.Longitude)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id.Remove(0,10)">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCcars/Views/Companies/Edit.cshtml
@model MVCcars.Models.Company
@System.Globalization.CultureInfo.CurrentUICulture
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Contact.Name" class="control-label"></label>
                <input asp-for="Contact.Name" class="form-control" />
                <span asp-validation-for="Contact.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact.Title" class="control-label"></label>
                <input asp-for="Contact.Title" class="form-control" />
                <span asp-validation-for="Contact.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExternalId" class="control-label"></label>
                <input asp-for="ExternalId" class="form-control" />
                <span asp-validation-for="ExternalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Line1" class="control-label"></label>
                <input asp-for="Address.Line1" class="form-control" />
                <span asp-validation-for="Address.Line1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Line2" class="control-label"></label>
                <input asp-for="Address.Line2" class="form-control" />
                <span asp-validation-for="Address.Line2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Region" class="control-label"></label>
                <input asp-for="Address.Region" class="form-control" />
                <span asp-validation-for="Address.Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.PostalCode" class="control-label"></label>
                <input asp-for="Address.PostalCode" class="form-control" />
                <span asp-validation-for="Address.PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Location.Latitude"  class="control-label"></label>
                <input asp-for="Address.Location.Latitude" asp-is-invariant="true" class="form-control" />
                <span asp-validation-for="Address.Location.Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Location.Longitude" class="control-label"></label>
                <input asp-for="Address.Location.Longitude"   class="form-control" />
                <span asp-validation-for="Address.Location.Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCcars/Views/Companies/Index.cshtml
@model MVCcars.Models.GenericModelClassViewer<Company>
@{
    ViewData["Title"] = "Company Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Companies" asp-action="Index" method="get">
    <p>
        Search in company name: <input type="text" asp-for="Searched"/>
        <input type="submit" value="Ordina Per" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.list[0].ExternalId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Contact.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Contact.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.list[0].Fax)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.list) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.ExternalId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id.Remove(0,10)">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id.Remove(0,10)">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id.Remove(0,10)">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>